#!/bin/bash
awk -v WATER="$WATER" -v STIR="$STIR" '
BEGIN {
  water="water"
  stir="stir"
  bestchol="bestchol"
  # function to clean input by allowed chars
  clean = function(str, base,   i, c, res) {
    res = ""
    for(i=1; i<=length(str); i++) {
      c = substr(str,i,1)
      if(index(base,c)>0) res = res c
    }
    return res
  }
  # function to convert from base to decimal
  to_dec = function(str, base,   i, c, val, res, base_len) {
    base_len = length(base)
    res=0
    for(i=1; i<=length(str); i++) {
      c=substr(str,i,1)
      val=index(base,c)-1
      res = res*base_len + val
    }
    return res
  }
  # function to convert from decimal to base
  from_dec = function(num, base,   res, base_len, r) {
    base_len = length(base)
    if(num==0) return substr(base,1,1)
    res=""
    while(num>0) {
      r = num % base_len
      num = int(num / base_len)
      res = substr(base,r+1,1) res
    }
    return res
  }
  w = clean(WATER, water)
  s = clean(STIR, stir)
  sum = to_dec(w, water) + to_dec(s, stir)
  print from_dec(sum, bestchol)
}
'
