#!/bin/bash
echo $WATER $STIR | awk '{gsub(/./,"& ",$1);gsub(/./,"& ",$2);print $1,$2}' | tr 'water' '0-4' | tr 'stir' '0-3' | awk '{print $1+$2}' | bc | awk '{do{printf substr("bestchol",$1%8+1,1);$1=int($1/8)}while($1>0);print""}' | rev
